#!/usr/bin/env php
<?php

namespace Netmosfera\Incload;

//[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]

use Symfony\Component\Console\Application;

//[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]

$autoloaders = [__DIR__ . "/vendor/autoload.php", __DIR__ . "/../../autoload.php"];

foreach($autoloaders as $autoloader){
    if(file_exists($autoloader)){
        require($autoloader);
    }
}

require(__DIR__ . "/src/IncloadUpdate.php");

$application = new Application("Incload");
$application->add(new IncloadUpdate());
$application->run();
